controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_like_recipe:
#     path: '/like/{id}'
#     controller: App\Controller\LikeController::like